name: Run tests

on:
  push:
  pull_request:
    branches:
      - master


jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
        poetry-version: [1.0, 1.1.6]
        os: [ubuntu-18.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: View poetry --help
        run: poetry --help
      - name: Install dependienies
        run: poetry install
      - name: Build coverage file
        run: |
            pytest --cache-clear --cov=localpdb localpdb/tests/ > pytest-coverage.txt
      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2