name: Run tests

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6.13
      - name: Install dependencies
        run: poetry install
      - name: Run tests with pytest
        run: pytest